// Generated by CoffeeScript 1.3.3
(function() {

  module.exports.doesTemplateReferenceIAM = function(compiledTemplate) {
    var key, resource, template, _ref;
    template = JSON.parse(compiledTemplate);
    _ref = template.Resources;
    for (key in _ref) {
      resource = _ref[key];
      if (resource.Type.match('AWS::IAM::.*')) {
        return true;
      }
    }
    return false;
  };

}).call(this);
